export interface Country {
  name: string;
  code: string;
  currency: string;
}

export const COUNTRIES: Country[] = [
  { name: 'United States', code: 'US', currency: 'USD' },
  { name: 'United Kingdom', code: 'GB', currency: 'GBP' },
  { name: 'Canada', code: 'CA', currency: 'CAD' },
  { name: 'Australia', code: 'AU', currency: 'AUD' },
  { name: 'Germany', code: 'DE', currency: 'EUR' },
  { name: 'France', code: 'FR', currency: 'EUR' },
  { name: 'Pakistan', code: 'PK', currency: 'PKR' },
  { name: 'India', code: 'IN', currency: 'INR' },
  { name: 'United Arab Emirates', code: 'AE', currency: 'AED' },
  { name: 'Saudi Arabia', code: 'SA', currency: 'SAR' },
  { name: 'Singapore', code: 'SG', currency: 'SGD' },
  { name: 'Japan', code: 'JP', currency: 'JPY' },
  { name: 'China', code: 'CN', currency: 'CNY' },
  { name: 'Brazil', code: 'BR', currency: 'BRL' },
  { name: 'Mexico', code: 'MX', currency: 'MXN' },
  { name: 'South Africa', code: 'ZA', currency: 'ZAR' },
  { name: 'Nigeria', code: 'NG', currency: 'NGN' },
  { name: 'Kenya', code: 'KE', currency: 'KES' },
  { name: 'Egypt', code: 'EG', currency: 'EGP' },
  { name: 'Turkey', code: 'TR', currency: 'TRY' },
  { name: 'Spain', code: 'ES', currency: 'EUR' },
  { name: 'Italy', code: 'IT', currency: 'EUR' },
  { name: 'Netherlands', code: 'NL', currency: 'EUR' },
  { name: 'Sweden', code: 'SE', currency: 'SEK' },
  { name: 'Switzerland', code: 'CH', currency: 'CHF' },
  { name: 'Ireland', code: 'IE', currency: 'EUR' },
  { name: 'New Zealand', code: 'NZ', currency: 'NZD' },
  { name: 'Malaysia', code: 'MY', currency: 'MYR' },
  { name: 'Indonesia', code: 'ID', currency: 'IDR' },
  { name: 'Philippines', code: 'PH', currency: 'PHP' },
  { name: 'Thailand', code: 'TH', currency: 'THB' },
  { name: 'Vietnam', code: 'VN', currency: 'VND' },
  { name: 'Bangladesh', code: 'BD', currency: 'BDT' },
  { name: 'Sri Lanka', code: 'LK', currency: 'LKR' },
  { name: 'Qatar', code: 'QA', currency: 'QAR' },
  { name: 'Kuwait', code: 'KW', currency: 'KWD' },
  { name: 'Bahrain', code: 'BH', currency: 'BHD' },
  { name: 'Oman', code: 'OM', currency: 'OMR' },
  { name: 'Poland', code: 'PL', currency: 'PLN' },
  { name: 'Norway', code: 'NO', currency: 'NOK' },
  { name: 'Denmark', code: 'DK', currency: 'DKK' },
  { name: 'Finland', code: 'FI', currency: 'EUR' },
  { name: 'Portugal', code: 'PT', currency: 'EUR' },
  { name: 'Greece', code: 'GR', currency: 'EUR' },
  { name: 'Argentina', code: 'AR', currency: 'ARS' },
  { name: 'Chile', code: 'CL', currency: 'CLP' },
  { name: 'Colombia', code: 'CO', currency: 'COP' },
  { name: 'South Korea', code: 'KR', currency: 'KRW' },
  { name: 'Global / Remote', code: 'GLOBAL', currency: 'USD' },
];

export const CURRENCIES = [
  'USD',
  'EUR',
  'GBP',
  'CAD',
  'AUD',
  'PKR',
  'INR',
  'AED',
  'SAR',
  'SGD',
  'JPY',
  'CNY',
  'BRL',
];
